### ISSUE TITLE
Include controls for modeler view in this package instead of bpm

### ISSUE THREAD

**Issue by nolanpro** [ProcessMaker/spark-connector-send-email#6]
typeEmail.js should live in this packge, then get published on install. I'm adding some ideas in the branch feature/6 but we should wait until the new package installer system is finalized before implementing

In BPM, we'll need to
- remove `case 'EMAIL` in ProcessMaker/Providers/ProcessMakerServiceProvider.php
- delete the typeEmail.js file (it got moved to this repo)
- remove it from webpack.mix.js

**Comment by marcoAntonioNina** [comment]
need 
https://github.com/ProcessMaker/spark/pull/1758
